printf("%s","Transcript show: 'write(\"fun p n=print(Int.toString n^\\\" \\\");p 0;p 0;p 130;List.tabulate(127,p);String.map(fn c=>(p(3+or");
printf("%s","d c);print\\\"-1 0 \\\";c))(\\\"proc f {n} {string repeat \\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\" \\$n};puts a::=~[regsub -all {.} \\\\\\\"};0 nruter;)\\\\\\");
printf("%s","\\\\\\\\\"eludomdne dnen[f 1];))\\\\\\\\\\\\\\\"[f 1]eludoM dnE:buS dnE:)n& n& n(etirW.elosnoC:txeN:)\\\\\\\\\\\\\\\"[f 3]  \\\\\\\\\\\\\\\"[f 3]& n&");
printf("%s",")9(rhC& n& s(etirW.elosnoC:txeN:)32*)1 dnA i-7>>)c(csA(-23(rhC=& s:7 oT0=i roF:\\\\\\\\\\\\\\\"[f 3]   \\\\\\\\\\\\\\\"[f 3]=s:\\\\\\\\\\\\\\\"[");
printf("%s","f 3]>teehselyts:lsx/<\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]>etalpmet:lsx/<>\\\\\\\\]");
printf("%s","\\\\\\\\])\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3]}0 tixe.sysn[f 4])\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 7];dne;)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f ");
printf("%s","3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]DO)a+\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]J\\\\\\\\\\\\\\\"[f 3]\\\\\\\\");
printf("%s","\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]+b+)8DOMn+05(RPER+c+)8DOM8%%n+05(RPER+c+)46%%n+05(RPER(tnirp;\\\\\\\\]i\\\\\\\\[tSBA=:nTNI ");
printf("%s","ODtBPU OTiROF;\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55];)'')\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\");
printf("%s","\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 119]}[f 8]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 5");
printf("%s","5]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247]tiuqn[f 256]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f ");
printf("%s","55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]@,:,4\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\");
printf("%s","\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 487]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\");
printf("%s","\\\\\\\\\"[f 17]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247]");
printf("%s","tnirp;);)n++,\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 24");
printf("%s","7]c%%\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247](ftnir");
printf("%s","ps=!)1,j,s(rtsbus;9=n(rof)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]");
printf("%s","\\\\\\\\\\\\\\\"[f 247];)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[");
printf("%s","f 247]n\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247](f\\\\");
printf("%s","\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247]tnirp;)s(htgn");
printf("%s","el=<j++;\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\");
printf("%s","\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 193];\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\");
printf("%s","\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503],*92p00+6*44+6**983\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"");
printf("%s","[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]}[f 8]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]");
printf("%s","\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503],:,4\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\");
printf("%s","\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503];}[f 8];\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f");
printf("%s"," 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 123]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1");
printf("%s","];))\\\\\\\\\\\\\\\"[f 381],\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\");
printf("%s","\\\"[f 503];\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]+");
printf("%s","4\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503])1<2%%m/n(");
printf("%s","fi;\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]:,4,g00\\");
printf("%s","\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\");
printf("%s","\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]{[f 8])2=/m;m;821=m(rof;\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\");
printf("%s","\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503],g00\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f");
printf("%s"," 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]{[f 8])n(f diov enifed\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23");
printf("%s","]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247]tnirp(rof;)s,\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f ");
printf("%s","23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 563]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\");
printf("%s","\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 197]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"");
printf("%s","[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247],/!/(busg;)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"");
printf("%s","[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 247]b=a;)''[f 64].''[f 64]+)a*''[f 64]-''[f 64]esle a>0 fi a-*''[f 64]+''[f 64]((tnirp;b=-");
printf("%s","a;\\\\\\\\]i\\\\\\\\[s=tni sa b:))s(nel(egnar ni i rof;0=an[f 256]\\\\\\\\]:i\\\\\\\\[d=d n[f 256]\\\\\\\\]2+n=i:2\\\\\\\\[d=+s:esle n[f 256]\\\\\\");
printf("%s","\\]n-0004+)s(nel\\\\\\\\[s=+s:))6+29%%)5-tni tsac\\\\\\\\]2\\\\\\\\[d(((egnar ni _ rof  n[f 220]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\");
printf("%s","\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 37]:9993>)78*29%%)5-y(+29%%)5-x(=n(fi;3=i;d=tni sa y,tni sa x n[f 256]:)d(nel<0 e");
printf("%s","lihw;\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]\\\\\\\\\\\\");
printf("%s","\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]=s;)\\\\\\\\\\\\\\\"[f 3]");
printf("%s","\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]a3e/****/}[f 8];0 nruter");
printf("%s",";)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 371]\\\\\\\\\\\\\\\"[");
printf("%s","f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 133]!}[f 8];)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]");
printf("%s","\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!!!}[f 8]}[f 8];)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\");
printf("%s","\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!!!!!!!)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f");
printf("%s"," 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!a''[f 64]c5Xdoseq\\\\\\\\[s(lazy-cat\\\\\\\\[ark3+IDENT");
printf("%s","IFICATIONaod4j#32GRAM-ID. QR.am{[f 8]4&PROCEDURE DIVISION.atk3&''[f 64]DISPLAY\\\\\\\\](map #(stratnC\\\\\\\\[l7z|6-.replace %%1");
printf("%s","al04h.3#|3D{[f 8]6u\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\");
printf("%s","\"[f 107]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 397]!ab.5?&abl5.(re-seq #ajk3v.{[f 8");
printf("%s","]1,45}[f 8]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]");
printf("%s","!ai{[f 8]6df=(n)->Array(n+1).join axl4h.2\\\\\\\\[?5n);console.logan|3G%%sac{[f 8]3%%,(ac|6~write-lineak?4ra\\\\\\\\[d std.stdio");
printf("%s",";void mara4we6%%B7{[f 8]\\\\\\\\[class QR:Application{[f 8]void Main(){[f 8]Printa,a6bBIPprinc #{[f 8]f(akB6Lc3pmain(_)->#{[");
printf("%s","f 8]f(8)}[f 8]nio:fwritea{[f 8]aPa5abFOifabaOh3abBM{[f 8]>(#{[f 8]f(agC\\\\\\\\[sI4G:ab<6;\\\\\\\\[4Jc2\\\\\\\\[ ab93O\\\\\\\\[4K; : B A");
printf("%s","ah;6E\\\\\\\\[4MWRITE(*,*)ak:6;\\\\\\\\[4RA ; : C B TYPE .aq93O\\\\\\\\[4C''[f 64]ab:3O\\\\\\\\[6>R ; : D Saj;3O\\\\\\\\[67ogram QRai{[f 8]3");
printf("%s","O\\\\\\\\[4E\\\\\\\\[8x\\\\\\\\[8x ab86.\\\\\\\\[4C(&ac93O\\\\\\\\[4EC Sad84G\\\\\\\\[4Gf8@5ab3>p\\\\\\\\[6P:=OutputTextUser();\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\");
printf("%s","\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]WriteAll(s,(#{[f 8]f(51a*7CV\\\\\\\\[P/nabaP:0ab3Ix\\\\\\\\[4Kset\\\\\\\\\\\\");
printf("%s","\\\"[f 3]\\\\\\\\\\\\\\\"[f 3](\\\\\\\\\\\\\\\"[f 3]& fLbV &\\\\\\\\\\\\\\\"[f 3],)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3] printaj94C\\\\\\\\[4C-ab:4I\\\\\\\\[8/pabd8?");
printf("%s","20ac4Bl\\\\\\\\[I|ackage main;imporar:4E\\\\\\\\[4Efmtad94Y\\\\\\\\[4Y;funcafcR(fmt.aea5Lb6I2G}[f 8]\\\\\\\\[7galgoritmo QR;in#{[f 8]f(2");
printf("%s","96aw:3R\\\\\\\\[7d136)}[f 8]xC3#{[f 8]f(4096)}[f 8]xADcio imprima(a&b?~>A-\\\\\\\\[FD=#{[f 8]f(4ag<=?\\\\\\\\[?99ab8\\\\\\\\[a\\\\\\\\[6/454");
printf("%s","ad:5;\\\\\\\\[<i822ad25;\\\\\\\\[6.a5<2ab:5:\\\\\\\\[8841acM<iFIc192)}[f 8]nshowak=?5\\\\\\\\[L.int''[f 64]main=putStr(aqbPm5A?\\\\\\\\[60a4");
printf("%s","D01ac8>m\\\\\\\\[:j54ac:59\\\\\\\\[6995ac>4O\\\\\\\\[JRaIb09ac9A<\\\\\\\\[8H328adw3O\\\\\\\\[4D\\\\\\\\[8H\\\\\\\\[Y/bM{[f 8]functionaib?D{[f 8]neko");
printf("%s",".Lib.print(&ara=:23ac:8s\\\\\\\\[Pg15acrEh\\\\\\\\[4D\\\\\\\\[SA\\\\\\\\[?C77ac;?N\\\\\\\\[N-632adBYZ\\\\\\\\[88541ad5\\\\\\\\[D\\\\\\\\[88aE+96ac23O\\\\\\");
printf("%s","\\[5hprocedureaja@,);i:=c:=0;s:=(aoCA8\\\\\\\\[T%%6ab6?O\\\\\\\\[69aVw70acB5E\\\\\\\\[A835ac;8w\\\\\\\\[PD03ac34D\\\\\\\\[:-aK\\\\\\\\\\$!41ac::-\\");
printf("%s","\\\\\\[D#97ac2:-\\\\\\\\[6X.classagc38QRaca3~super agn4/a3;method ahh?va?{[f 8]\\\\\\\\[Lace3;a?o;)V ;\\\\\\\\]&&&&n.limit stack 2&&&&n");
printf("%s","geta&b>2java/lan\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]g/System/out Ljava/io/Prin");
printf("%s","tStream;&&&&nldc a8GWH\\\\\\\\[:j03ac:I(\\\\\\\\[6960acCI(\\\\\\\\[WG80ac:4E\\\\\\\\[9v83aco7/\\\\\\\\[4D\\\\\\\\[9w\\\\\\\\[71class QR{[f 8]public ");
printf("%s","static void main(a&b3y\\\\\\\\]v){[f 8]aea3n c\\\\\\\\[\\\\\\\\]=new String\\\\\\\\[99999\\\\\\\\],yaykLlaF24abO8tGB\\\\\\\\[54ac,4D\\\\\\\\[4D\\\\\\\\[");
printf("%s","?1F<d36ac:3R\\\\\\\\[694024aeB?1\\\\\\\\[:l27acN6>HFE5ab2Cv\\\\\\\\[6=o?939ac:DX\\\\\\\\[8t24actDY\\\\\\\\[4D\\\\\\\\[DY\\\\\\\\[?8149ad98%%\\\\\\\\[6:4");
printf("%s","896)}[f 8]qah?8-\\\\\\\\[8-915ad9=O\\\\\\\\[8-723ad2:}[f 8]\\\\\\\\[4Y,z=y,s=ahi2\\\\\\\\[&ab?;O\\\\\\\\[:j6499ae83R\\\\\\\\[69988ad23O\\\\\\\\[6:c6");
printf("%s",";4)}[f 8]q#{[f 8]f(4171am43R\\\\\\\\[::a3Q215ad13O\\\\\\\\[4D #{[f 8]f(1638ajB7i34,#{[f 8]f(127akA6tb2aJa5a/b/b1b|b-b3a5bobAb1b.");
printf("%s","bzb1btb,a-bdbeaHb|b,b/b.b1b3a-bebxbzbxb7aHbib.b|bwa-b,btbDa5a6b:buaJbocta/bsctbHaHb3cscubfbxbvb3b|b.b-aUbxbtbwbxb1a8b-bN");
printf("%s","bxaGaJbQaHc*c,c.b-bcb4bub+b|bva:clbDaIa:bGcxb-cxa/aHbybWa-b|cVbc*F3R);Print(#{[f 8]f(3)}[f 8]ap|2\\\\\\\\[j3o\\\\\\\\\\\\\\\"[f 3]\\\\");
printf("%s","\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 187]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f ");
printf("%s","1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 317]!abi2\\\\\\\\[!!-bna=a;a;aCaDa?bpb:b>b2cDb2b3b1a5cNbHaMb>bzb+b.bubtb+b");
printf("%s","na@aFaBaEaBb7cVaEbpbvcxd1a/bcbea-d1d1a?a?aUaNaVd7cxaBaPa-a>a;a?a-d4d6d>bod9biaVbfaVaOaYaRdIbod@dHd>d9bBbDb3dSd@a5aGebaPd");
printf("%s","Sd9dxb+aGeedId@efcPenaPajaMc+b{[f 8]b.efa-a4cFb-bxekaGaFe-e-efaHdYbEefdpd7eoeremd>e7dWa?a;btb2b2bxb,cEb8eyeaerb:efb<a;b,");
printf("%s","bxb3ewbweydlbtc-d0era-b5cheQeWaZcmeqe:aPe5d1d@a6efb:a;bxbEb1b8bVdZeyb+bwdlb1effzerf{[f 8]ffefe9e6egdId9b,elbwbucwboa1cta");
printf("%s","1e2eGfffhd?f.f*f|fAf@fCf-f}[f 8]fEfBfGfDfif?fIfMfKfFfOfHfQfJf>fPfUfRfWfTcte;fNf>f,fSd7dXbCbEbye4fVgafLgfgpfYgcgngmdTgogr");
printf("%s","gqgtfXgzfZgvgugbgyg*g{[f 8]g.g}[f 8]g,gxg3g|gsg0g6g2g5g-g9g7g;gwg:g4g=gAg<gDg?gBg@gHgGgJgEg+gFgLg/gOg1gNgSgegAd9a0bTbVbX");
printf("%s","aIdlbwc.a;b{[f 8]aKgMhigPgShjgRhmg8hlhkhog\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]");
printf("%s",">hsgChqhnhrhyhxh{[f 8]hphugIgQh}[f 8]hzh-h|hth.h1h0hvgMb-fteWcJfef-f=gnfkeHb/b4b3b2glh2h5hFh+hwh/hKh3hLhGh4hIh*gKhJhMhUh");
printf("%s","OhNhQhHhShRh,hVhYhPiahZichWidigifiiiehXilipiniqikisivhTijiyioiuixi{[f 8]iziti+iwibi}[f 8]i,i*i2i1i4iwgUgIghdZbrfxbDbzhEi");
printf("%s","mi0i.ihiAiDi/iFiCiGi@iIiriEiHiNiJiOiLiKi|iSi-iMiPiXiRiQiTjaiViUi3iBiYjbjhjdjcjfiWiZjjjmjei5jnjijojvjujxjkjpjsjrjgjwjzj+j");
printf("%s","qjlj|j/j*jyj.j{[f 8]j2j,j3j0j5jtj7j<j4j-j9j?j6j>j8jBj@jDj;hIi7gJd9b>b3b.e?bvb|b|i?jAjHjFj=jWjCjXjEkbjVkcj}[f 8]kdkgkfkij");
printf("%s","1khkkkjj:knjUkpjGkrkaklkokmkxkwkzkqkyk|k{[f 8]ksk}[f 8]k,k+kuktjZk2jYk4kek-k0k7k3k6k/k:kvk*k?k.k@k8k<k5k>kAkGkCkBk=k1kEk");
printf("%s","Lk;kJkMk9kQkDkOkHkKkRkUkIkVkSkPkYkWkTkFkZlhlelclgljlaldlblnlllplilslmltlolxlrlykNlzl}[f 8]l|l+kXl*l-l,lfl0lkl2lql4lwl.lf");
printf("%s","jJg<i9e3erh=lul@l{[f 8]l/lCl1lDl3lFl5lHl7l6lvlMlAl8lGlElRlQlTlIlSlVlUlKlJlN\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](");
printf("%s","etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]lBlWlZmdmblPlXmimelYmglLlOmnmcmlmomamsmfmumrmqmjmmmtmymkmzmwm+m}[f 8]m{[f 8]mvm.m,m*m3m");
printf("%s","/mxmhm4m2m5m-m7m:m8m1m?m<m9mBm@mpmAmDm|mFmImEmKmHmLm0mJmMmQmOmNm6mTm;mVm>mPmSmRmUnbmWndmYmXm=nimCmZncnannnmnpnenonrnqngn");
printf("%s","fnjmGnsnvnznxnlntn+n{[f 8]nun}[f 8]nhnkn0nyn.n1nwn5n|n7n4n3n,n/n6n;n-n<n9nAn?n=n8nDnBn@nInEn:n*nJnHnKnCnMnPnNnGnUnRnOnXn");
printf("%s","Vn2nWnZkkl:gFjLbteEn>obokoaomojonnFolooosoqopnLovnQoxnTorouotowo*oyo,o{[f 8]oznSo1nYo|o+o}[f 8]o6o5o8o-o7o:o9o/o.o2oco;o");
printf("%s",">oBo@o4o<oGoCo=oEo0o3oLoAoJoMo?oQoDoSoPoOoHoKoRoWoIoXoUpcpaoYoTpfpdpbpkpgoVoFplpjpmpepoprpppipwptpqpzpxoNpyp|oZp*p-p}[f ");
printf("%s","8]p/p,p0php.p1p5p3p2pnp8psp:pvp4p7p6p9p@p;pBp=p<pupGp{[f 8]p>pAp?pLpKpNpCpMpPpOpEpDpHp+pQpTpXpVpJpRqcpYpSqapFpIqhpWqfqip");
printf("%s","UqmpZqoqlqkqdqgqnqsqeqtqqqyqwquqpq|qzqxq-q}[f 8]qrqbq.q,q/q{[f 8]q1q4q2q+q9q6q3q<q:qjq;q>qvq@qCq?qEqBqFq*qDq\\\\\\\\\\\\\\\"[f 1");
printf("%s","](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]GqKqIqHq0qNq5qPq8qJqMqLqOqVqQqXqSqRq7rcq=qTqWqUrhrgrjq");
printf("%s","YrirlrkraqZrdqArmrprtrrrfrnryrurorwrbrer*rsr|r+rqr/rvhSoeeha?bBbKbMb,eybQe4b.hBhAf;f-h?ffaHbucbbDeyb6bCb3bxe4a4kfa4a4b2a");
printf("%s","8a8bra8e0rSa8bvb{[f 8]fyeWa@aCa8rMeraHrYa9rWsirYsascffa-a@aAsgrXrTspeyaAa?svsnrTaOsmrDsosbeysts}[f 8]s.rTf:eyb/btbvb*s-f");
printf("%s","-sjsxs0eWaBaFs3s=rYcbs<fKs>rZs@sra>a?sushs4a8a9s|swsKsqf-a-aAa>sDsIrYaCa:tasHf>sJsyeWs{[f 8]tctjs/sXfKsZtbsQsErTb-a<a@sU");
printf("%s","s*sWs1sftvtds?trf>sZa=tognsJb-a:dZtit5tqt+t4gvsJaOaEa9spt:t?t<tmt3t-tprTdjbufxeyb4b-rOkkrQa9tSj:rQs8s:tEd@tksLsYsBt>uctG");
printf("%s","sra@aEuhaPudt0gnsst,sVbWbwubuoujsYaCtusVb-uxupt=tJt;t/eysNsPsVa;u,uztsu3unsJrSsVtlsrugu/tFu1sdu4t}[f 8]aQa?b7b*bbaCa<bhb");
printf("%s","abuaWb|aZb1aSbwbcb0b2uObjbhblbcbjbmb5bdbtaWb.beaYaEb|aDaCaOb.bdbmb7b,baaYa=bmaZdQbvaDbmb+bdaDbjb*vdbjblb5bgaUbzblbabkb.b");
printf("%s","jba\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]bjaDb5aEaCbvb7aNb,v9beb-b/b-beaCaEbzbaa");
printf("%s","Xb2bvvCaNb7aFa>aEuWbuaRbhbcaXtWjUtUwhjGrQaAuWvbbwbfb1beb,bbaYaSbmaFaAb*bjwzb7bgaYb/w+w-w/w.bgaFaXaSb/bda>a<b7elb1aNbvbgw");
printf("%s","9bhaDwAelbjuNvqb*bwbaaBaWbtaFaCaAb,aPbjbBvibmb.baaTbhbubabtvwaDaBaNbhbbaXb3vBaBaZbvaOaTvvaYvZxmxoxqxsa>aDb|bbxdwobibcbfb");
printf("%s",",aSwNa?aVbwbgaWw|bdb0aAb3vqv9v?bhb.aFaYdvaEaYaOxvxpa>vvaEb1x=vbb2xAb/b|x.x0aFx2x4x6bjaEaXb*uOxdb,xfybxjvTxSx1x3x5w|vybax");
printf("%s",",w{[f 8]blbdb-b.bmbdaTbibmbebtaAbzvYaWb1aFa@aDb7aPaUx{[f 8]aZb0biwRwkkuwjrPa4b0bdvFb-y5y7wRb1a=b/vNw>yox,a>bhywyyaPaQaUa");
printf("%s","@b*elbtaObvbdbkb{[f 8]b|yRa<b5baaUb.b{[f 8]aQbuxFaVaWb{[f 8]aSaXw=bzaRwWbzaQxLv:vbb+vGxyaEbeelblbzbvaUbjb+a>aFb-b7b|xAb.");
printf("%s","b5aSzhzjzlb5yjxUaRx4aTbexGaOxIb7aEb,bixGaNd;xWw|zAa?zCbgzEzGzIzKb{[f 8]bmzraObeaFzyx>x@xBbuzSzUzWd*xozOaNzQw}[f 8]aYxMx?");
printf("%s","z9{[f 8]kx/x1{[f 8]mbey2b0aRw;aGa\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]Ub3b-elaC");
printf("%s","{[f 8],zx{[f 8]vz|b,vvy:k=y<tTa4xtaEvhb,b3elwOzCwraRbyvNw.aPb0wxuPb3wNaCaNbzvebm{[f 8]1aGz.bvel{[f 8]Bb5aNaTb*bkbfuYbxaN");
printf("%s","bkaVb/w,b.b}[f 8]bcxrz@aXbmbmbcaBaSbdaEaAvWaSzo|{[f 8]{[f 8]Rb7xtaRbtaY0ZF3R);Print(#{[f 8]f(3)}[f 8]ap|2\\\\\\\\[j3o\\\\\\\\\\\\\\");
printf("%s","\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!abi2\\\\\\\\[!!w-|wbt");
printf("%s","aRb5aVz=zk{[f 8]Sbea?b.b9xtaS{[f 8]A{[f 8]Ce,{[f 8]3wqb.aDbyzSbhx4xk|{[f 8]a>baw+aUb{[f 8]aOaQaTb.b8bdb1b{[f 8]zNzPymbja");
printf("%s","QvrwXaBbmb}[f 8]yVbhb8aD}[f 8]aaPzVaAb.bgbtb/aZwryGyI|gb.aWbcbdb/{[f 8]Kb1aEy{[f 8]aCaWb,bctNb*aPb1b/}[f 8]c{[f 8]r}[f 8");
printf("%s","]ev7b{[f 8]aX|V|Xbdb,b+bi{[f 8]2bw|C{[f 8]Da>b6{[f 8]:kE{[f 8]<tXa4v+}[f 8]az4bkaSvXaTbzb}[f 8]xAb{[f 8]bi{[f 8]f{[f 8]6");
printf("%s","z}[f 8]|/xz|gb/v2aEbj{[f 8]0wvbwbmelb-aEb7zSa@b-xPv/bjb{[f 8]b4|ob5aRvK}[f 8]<{[f 8]saRb0z7x8b7vQaTb3aYwVwX{[f 8]u\\\\\\\\\\\\");
printf("%s","\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]zzbh{[f 8]7xyvA|Aa@aQ*<x>*?*haEb*vib7buviaAb{[f ");
printf("%s","8]bgbmaAaT*w*yw-v/za|{[f 8]a@y@*U*zaDbub3bkuXjNvRjN|Zb3b}[f 8]uP*f{[f 8]8*h|I|AaB*D+qz*b8beaByz}[f 8]vb/wqa>aAbu}[f 8]va");
printf("%s","Eb}[f 8]beb0b+xm}[f 8]Nkc}[f 8]Pwia4{[f 8]p}[f 8]dxXaPb,aVbvuXaEbxvRvs*Q*S}[f 8]vaWb2+{[f 8]uRbavrb8aRvzb*x.xFx>wya>bibl");
printf("%s","wvxF{[f 8]obvaPzI}[f 8]6a=bzv}[f 8]bmb8+c*Wv0+VaWbz+X+Vvb{[f 8]bb0aWbkbbd+b8elznb|bgbu+x+s*jaAbcbazo{[f 8]b{[f 8]gz{[f 8");
printf("%s","]*g{[f 8]?aV*Nb|x8aOwuvz}[f 8]uzl+Bb1bd**,.*={[f 8]idv{[f 8]lzDyZ|haSbcaEyyaD}[f 8]pzpaX}[f 8]*,Qyybtbexk|YaCc-aQaWbvbva");
printf("%s","Txkb.elbuaSb}[f 8]aVb.bwb8bcbta=b2aOaXaWzN+7kg+9wla4+=w|,-,/xtaDbw}[f 8]9a=b8aNa?b{[f 8]b*bgbkzebdaCb2z|tyb5aU}[f 8]jvMa");
printf("%s",">jNaZaXaEb/|x}[f 8]twY*>|kbdbzw8v5-rjQwfw{[f 8]d|ba,,btvWaQbjbib*xUaNbybc}[f 8]0bl}[f 8]v{[f 8]raP++*/}[f 8]eelaUaA-8-e.");
printf("%s","u+>b0{[f 8]raFaTxF|+,swOa=}[f 8]5b0aOb8{[f 8]Ob5}[f 8]6b/,mb1aOaF,-}[f 8]1bdwLbivNxl,d{[f 8]q{[f 8]saX*E,8+r{[f 8]?b8|A,");
printf("%s",",|Sb*vmaSb-|\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]K|Mb3b8aZaUbvb4aQaX-xaO,x}[f 8");
printf("%s","],vjelbgwTbi-*i/-,y;a4|xb+,m{[f 8]Bw+,H*F,9*ibfb/babczn{[f 8]aaX+@v+ww-uaWzMaXbj+V*OaA//+Awfb7bl-bb+bm+HaT+?wn+{[f 8]bmx");
printf("%s",",-ev>aXbdbi/l,uyNy/b/+o}[f 8]3vQaYb3aSaVbkbwaU-baEb8aUaWbhb4aS}[f 8]j*Pbu{[f 8]SvefvelaB.5+R.5aUb0+D+Fb.aPe?b7*1y8xUyTaF");
printf("%s","aUbwaB.n0ezqaA,z-ebk/laA.|w|,Ublzr-2xzb6zxbib{[f 8]bca>xFaU*..F-/bj,-baywzluWuY*v{[f 8]zzBzDbe/oiC/q{[f 8];a4zXxJb-a@b|a");
printf("%s","NaC{[f 8]v,J{[f 8]yxTzT0X0<0NaUb6b8uHb7b2wfb*b{[f 8],UaE+w*=*G{[f 8]?vMaCbm/VyXvRvk,nw7+e.:vNbmb*zg}[f 8];,dzHxJ,7{[f 8]");
printf("%s","w{[f 8]j+M+La>1xx8+51?zY1B1m.VbgxkyYvjbt1+{[f 8]h{[f 8]x,LzVbe/Y*nb21Ib.1X{[f 8]nxnxH1f1u}[f 8]gbicBa?bv}[f 8]}[f 8]blby");
printf("%s","aUb10Zi@1b}[f 8]Oa4.:bfaBb/{[f 8]T0nb4bfvrzw.J1C,K0V1p1YbvvNaS}[f 8]8wF}[f 8]laGwsws{[f 8]Bw=b,uZxfvwbab,b6b+y3bl|Db0/fa");
printf("%s","UbiaUaU1G,;y}[f 8],=b0bab}[f 8]vi1>2h1@zJ1M{[f 8]xaQbkb+2cb0b*b4.nvk-@vk+*y{[f 8]+|+or61e3d1l{[f 8]x1EvN3y{[f 8]j2fbd\\\\\\");
printf("%s","\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]b}[f 8]3g|f/}[f 8]aV0U1o*x+dbu2mbca?bwwXaX*k-");
printf("%s","O*;0A*u+*.C0sbv1U2viL2x+8a4vb1N24{[f 8]m3,2fzF1K1fb2b6aZaCbhb,aNzoa?aSstaVaR,r|g/0aTa>b+bt03b{[f 8]v}[f 8]{[f 8],16*{[f ");
printf("%s","8]xFbfaU3a+<}[f 8]=xX4saDza{[f 8]Q3@bfaT1k*PaYew2.}[f 8]W+U|8zo/:/0+3wWuLb3a=wK1haWwL+LaAzJ1Oxkb}[f 8]-6.3aObm+O}[f 8]4v");
printf("%s","yb3v.+fbw+m/K/MbgblaAblaZ*7aVvycgxBblwe{[f 8]BaR.SbgwCwGa>a=aN3Gi|3I-+a4aDaX+A5mwBwA4|/7zfy*wyaAbv5{[f 8]uN5}[f 8],q,saW");
printf("%s","b/b{[f 8]0gaAaEaEaU/?b4aPbk.:|kaDb0{[f 8]f-BaOd;,j/a*v*|-8aUy60raD/caXa@|J2434,obk{[f 8]@0L4zw|{[f 8]fbvby-=a@.*4lbk5?b/");
printf("%s","w}[f 8]1B1-xzb25}[f 8]*}[f 8]5Eb+aO|lbz|=vE525+.0a@bhbv3Q3wzKzm,5/;bvxjb/5riV5t/pa4b*|xzo+k}[f 8]u}[f 8]waZ-gbvbwaF,X,Rb");
printf("%s","ia>/Ybe5;bub{[f 8]b-|V..,ryY0K2h.G}[f 8]eaDb,06bc}[f 8]3v:.--Ezo1r6Y7a7c4Fb3bmaQ}[f 8]j2YuUvxaX*OaQ-wvp/2bc/4vhuUbl5?bw+");
printf("%s","hb1vkuH|f5zbf,X5z75a>aV5079765n7<50bvy6}[f 8]F|Z.5aVvO+o}[f 8]0x,41.R-Lbzxj.5|ZaS3Cbm09xbb\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%");
printf("%s","%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]}[f 8]xjaS0f7{[f 8]aVb1{[f 8]V+Mb{[f 8]wExFaRb,67jm691aa4b{[f 8]48/QaB/A");
printf("%s",".DwN0sb8aPblbmb|bea>blb4-F}[f 8]taDySb7xjba.Yyuz|bkbeb.,{[f 8]787;7:wA5z}[f 8]63@1rvRb+b-wY2mxrb7+o+fbkaR1k1,/{[f 8]0eba");
printf("%s","bXbk-KxcwYaA/B/y.Kz*a<bd-sbguX81aZb.a=1raZaB.E6V0MaFaVa=bt4FvTaZvHb+.,.y/6zM6a{[f 8]saVaYaVbi4OaT8Abibf/Wa?bc8ijs8k2wy>8");
printf("%s","T5xuS8<5o9>7=8:9C9?9B9E8;9B9laE-vwtvRuV6?}[f 8]Db3we8X-R.LvZa<uP-BaNa@9i9}[f 8]}[f 8]e9kb3aOvyaS+B{[f 8]+uS9l1r0/b{[f 8]");
printf("%s","/V7W2F2PaTtNzjbmb{[f 8]{[f 8]e/eb|aX.*b5be}[f 8]t:x-i5}[f 8]9F:29H:49Da=5j/297iw993H+;x9btxc9-4O1r8K.=aY*2wN+-b.:Gb7|2.4");
printf("%s","7?vn.Y{[f 8]8a<4|tN9224|L1PjNbcb,aO*ZaZ:m9m4y{[f 8]s:p+/-o9Sb+bg/l|X9{[f 8]1r-Fv-9D:3;w:59G;y5z-bbm9s.-*Zbd;gaR3nye*kbla");
printf("%s","Sb1b23Cb7+z+|/BbtaEbibb6Z+/btuVx8bh::iD:<5sa4;gwebm4Kbdxbyw;7e+7w5}[f 8]bl/Nbt,Nb.89;{[f 8]<d;x<e;z9B5,vY+Z.n;Pzo*y8q92b");
printf("%s","ubl4px9b.0@8M9V5:4daWaPaWa@bmaBaTdOa=7laV</y2\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f");
printf("%s"," 1]4WaSaEaW8xaU<4aP-n8?:dxXaV59aQw6aEa=<;b/aEaS<g;|9?;HgM;J68a4<f<T<h:4-n/XaV*n1r4|bma=aTzhaOaAaSaAaWaTaS/Wa@aTaWbaaE-r7");
printf("%s","nz1;hbv6W4{[f 8]3N1q3SzJb.<7|m5paR/e-yaUy{[f 8]d|b/bi-@b2bkwOvsbdwF<V<M<U=@;z:c9n6b0N+fb8bg<Ohk<Q8\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[");
printf("%s","f 3](\\\\\\\\\\\\\\\"[f 3]& fLbV &\\\\\\\\\\\\\\\"[f 3],)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3]ja4bm=x=zzR5V*V17vb,=vj6<aB06vyb2bmaN216paEbf:U<?=E{[");
printf("%s","f 8]saY9T>h>j:X.W=b=T+dvf1r>o0AaD9s>v,ov41RaVb{[f 8]x8aW;o5*<@w|<>e+zTb/=B8:=KgR=M985v<L>A=A>BwBaC4x=y0M6|,4.0+Y1Tyyz8|W");
printf("%s","+Qvnb,v}[f 8]bl+Bbjdt.,rL;b.y=cvg>4w}[f 8]|S+hb0{[f 8]0;b>C?m=?>D<M,iwYb3{[f 8]Ty?6-5V><hp>>:;a4=U*{[f 8]aW.U>*=V3//*bc.");
printf("%s","/+XbiaDelya:W1o:Yxkbm>J7g?f656<}[f 8]0,Bvsba-IvM|yuWb,?n>:?p?N<T:,x*+OeOaXaC1|,U/:6o8Nbc,U9j+4=7.<b8zn5Q+Ra==Z?yg>?{[f 8");
printf("%s","];I=O8Rww0Sxlbe=>?M?L?O?o<fa=7Uw57XzM,U:I+A.1yeaX.56|7l{[f 8]b/0:f4paTa@bvaYb,<t7va=x|aXb6b4ba5g8;6Rbz@|@M@y=?@nhv@p<Pa4");
printf("%s","<L8L/z<zbbxc=0ZF3R);Print(#{[f 8]f(3)}[f 4]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 5");
printf("%s","]ap|2\\\\\\\\[j3o\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 50");
printf("%s","3]!abi2\\\\\\\\[!!Q9o{[f 8]M?2,rb9.g8naXz6:o/0-=-t+Rb2xR?.4tzfb,c,w,>{[f 8]@N?p-Av60a+Q+fa=/lAb=F*QbeaT@O?Ma=<8a@@1v1bxxA3}[");
printf("%s","f 8]231o{[f 8]|b5@QhI@S=La4?f4W.y}[f 8]9dj4W@5>s:Za>*QaSbhbfx2b3aVa@aW,}[f 8]aG>p8N/vA?=}[f 8]3b1L3@+Q<I8v?K79Anb8aS-AAz");
printf("%s","@zBtBs5{[f 8]<G:U=9*B:Ub3a?*QaO>r33=UABhSAD>=a4v/+fbb*QA/;j|P1rAL@hb/B9}[f 8]>@x@{[f 8]76535-}[f 8]I?f,U,63@b-6laQ.S.Rww");
printf("%s","5caYcgaWaYxhA4;{[f 8]wLb,vYv5y-wa+Ma=|xb*yYb,3/1BxOw-b||+b{[f 8]4+,I1W=|1Y8C/2aXBb8hy=tVy=*@b{[f 8]4|zabb6.=*zZ489F+A.A6");
printf("%s","+BXBuC9=?0sby-Kbe;==68-b{[f 8]uWvz2Y-o8@}[f 8]w2eAs4}[f 8]Cr-b+g/lC:5o}[f 8]@?V4ndQb|7DaD.C+Y.uB0gEB2?za4xX-Kb+bu03bw+{[");
printf("%s","f 8]/S/C/E>ja@aNb->obia=0kaO?JCRuN}[f 8]v:y-@wawf@=aY-w7h}[f 8]aBJ*=C\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\");
printf("%s","\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]nxQ>K5-4P1U8Y*HB-x15W17C{[f 8]z*wev4byx>?wB.>wD}[f 8]Bw@;a@b73p<b7r6s?Y3@bkDdgSDf@o/s>ab-+maS");
printf("%s","C;A5*T.<b.v}[f 8]uVuT{[f 8]PCO857p}[f 8]6?T?VvpBC5obmbbb0b6b|;ubjelbm2p73}[f 8]+6H*Jxdbk9Nw7vj/3bhb5bb5JaZb-vE-96O5?b.}[");
printf("%s","f 8]}[f 8]E0aTD}[f 8]{[f 8]ZaGyW,jxEb-,-yGfcfvuT{[f 8]vD7,,*RaT9kAq|Zx6vy0e,U|{[f 8]aA4rCLs9DXefDZ@Ra4wB>ab05ab6=C?J0*==");
printf("%s","}[f 8]t7ZaS7s*O:Ub/DEeO:i:k7W3pbj|x7R,-vsEg>DElbwEnDNbv,W?0vW4|s9Bvv}[f 8]ypel@e-v3PCLbub/<;bkbzbwaWtNb5aY:|yVfvwfwWF4Ek");
printf("%s","@46f5Ywe-a}[f 8]2vsF8uT=9/}[f 8]BWa>FjerFlAC<S@N>FaU93?E,W|q7.}[f 8]ubl1J2h,fvvve;d|||7:fvQ8u?>.00sEKBW+Pzn{[f 8]@F0F27S");
printf("%s","Gg@tEnb0uXbm.p}[f 8]w?5yy<;:ybe@wvg-r-taZ56be/d7mbebXGI@LF6:32Jb3y3y{[f 8]{[f 8]2bl32D@?*+e>{[f 8]bzbfBB=AGnffGpB1@Uw:4-");
printf("%s","8BD<9U*@|gb1vE|=b.=ya>EY5@b+yRa@;cv4b|-Z+Tb1cFbg*Ob|el*OvmxBb5.Z>G=RbjC.b{[f 8]}[f 8]f>Q}[f 8]6*c70BvwCbib|5;bdxOb-|m.,a");
printf("%s","V6rANvSx@b-8gv7z/:UvW?X<x@X\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]z*C0CL>X7:aA,2?");
printf("%s","3vYG.a@|7?A03}[f 8]ubm}[f 8]1ba,xb2Hpf-HrDea4.s2X7V/3zMaZ5@9j3X.*@WD=-3:,3v?faV,xEq}[f 8]k-vDL8:ATaRb2vR4Yvy|I-v*OA4aBaV");
printf("%s","/caW*S.s4KuTuV+i5j7KxjaN0F5SbiaQa>H+D1B@.}[f 8]2X;Qb3x4bj,2aNH-vp}[f 8]a6P</bv8KvWI|b+b}[f 8]fcy*//Gl?mI+fKI-DYFn|hHfwOv");
printf("%s","W6HaRaV9TET-1<yDDIGb2J;?=6g1i+faR8:J<Jlw|<9bm<;aVaEaN|+.X6|/-1rCz>{[f 8]byIr>a{[f 8]T39Gda=b.aRwL,z,|C1BgxJ;c5+}[f 8]b?f");
printf("%s","0G8V38c,Hay3GXEw:3/6J1f>J3Fka4@K+X2C?Na=@f4KwfvP93jNwrchwfvk,{[f 8]/>FYGhbXGBb0GD4W}[f 8]xx.7m}[f 8]6Fz93@*aD7y|y1/5Z>m6");
printf("%s","XD463bc00blIPaEASa?aZb*BIIixNxP,=6U;i}[f 8]e|AbbIh/0aXbtI5769iCq7hKD>/d+b,3|J@+s2s??6VK*gnK,Go-.=F|ub7b-:vJZIr|.+{[f 8]b");
printf("%s","7=7.4bwbb7eLw?f/6K/=;92>g/{[f 8]4}[f 8]|h}[f 8]+52*ZaRv+K{[f 8]:5d+yHuMAz}[f 8]{[f 8]8|HAvjbuKNx;IszfvbyYI>KSxXyK7b>{[f ");
printf("%s","8]vByyFeb6Hg0-Hi5*L/gvL1HqB4yuwya?b*b9.A.i}[f 8]vba-NyW87aXz7}[f 8]vxo.O*bvxwwE6.X@O7Ob,aY}[f 8]0ywwLx\\\\\\\\\\\\\\\"[f 1](,\\\\\\");
printf("%s","\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]GG+b7INx@I:Hy*Hba5}[f 8]v.d*b2-5bJ9HFR6J1TLI<z>}[f 8]DJ5X>/v");
printf("%s","CE?b,NcaCy@M?6=z8yrytEC/}[f 8]/+/-DUL*-3.C-eCT?W}[f 8]a48@14Dw,w2w0N*b7Mwd@MyI,a4w3w5>9LR8:=850{[f 8]-w=w?-e=I=H<XN?wIwK");
printf("%s","wMMeJW?fbdaY5Q,*6,KmxwzYKp/-@8+Axcvw}[f 8]v.5KN>lLlxXyVbwb}[f 8]aDyyx-FIaOLH=x3cxKA=buxD,cKn3xCt{[f 8]jJk1rxZN/aPN1J2e{[");
printf("%s","f 8].6yd}[f 8]v/uOfxFA5/:AdF@aWFq21ETbcNmM|yxbhbk|AyB9GA<Ntxzzw3e3*CvzEH?ch|Z,iwvLP=cc-5}[f 8]=400bbwOOo3Q@sOOFIy1uPLXbi");
printf("%s","KkwQy,bl.,?=8>NtOzO|K+@U-4NN2izJb,aW2Y|67?@@F99lOUMJ3MBe1Y8REFHM8<{[f 8]3DIHh+dvjb|?FBuOw?fOB1VOGP-aTbd6EvkOEOWOHGKAxOuA");
printf("%s",">{[f 8]{[f 8],Mbw<>OCaDztbmw.A<b3-=zFPna4C*{[f 8]=5d07b3/?vz-8/Wx,;Db8aOb-,lbcaY,r-=vG}[f 8]vIK-e?=3D-=FcK2wJ}[f 8]jb0-=");
printf("%s","AM?:|M-B.?|q8q|Y;78;v{[f 8]2|yXQz}[f 8]ow5?=QwQ8w?bu}[f 8]{[f 8]-A;ozl}[f 8]x+fQf-7aO+fyw{[f 8]uQDaOQF++uPb/M:v{[f 8]ElQ");
printf("%s","4b2/x@*-@b3?Ba=b7NU>TaXb+bzGYP17<PYQa}[f 8]Q@M-=.:NIaWDnxIbe\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f ");
printf("%s","1];))\\\\\\\\\\\\\\\"[f 1]}[f 8]?M:w6vi.XE@Msa?DAv/PSz,aGMJ>hMUxTR2LJHlImvv=cPTaTbvBLIAK>>ybubhb2aPP0>:aAa=aPw6b3M@J=Libc=Pb2aN7");
printf("%s","tbfPlIj+sMT|AzjMXz*}[f 8]cRnPY=F.sv2|=HC0MDwbkaNaAb2b*Dw:@DC+szfydwzv2E;zizONcaBblb6zOaDxO1;blbf*Yd*ch-gv29vziaQzL|-bdb{");
printf("%s","[f 8]|A09aCMOS,.N6Jb4.,fc|APNaG;4RkSOEwa=/c+Y|{[f 8]xgb6|Ab1aQ*2vxSTvCaObcvY}[f 8]t.,=7d*aNb}[f 8]z}[f 8]{[f 8]eSfy=00SU");
printf("%s","Jdel</*yyBbwaQ;4:-bzM@*7|O?n:-S+aN>eCmLi5;z+E,Sjy*Q6Ts>ebV2-CLbmSraYbk<11j>{[f 8]T=Na17T?+TR9TsvXNfSU8x|A5>2WPx/4y66,v}[");
printf("%s","f 8]zK>UP4Mt+d8xLbIH=jKROa>5BaK3y6IeAsTp{[f 8]=aD2KaPaR/*1rH=SjvHf1aGR,wRN7U+IE9Gela?bhbzaNv4R8TGv/8xIuaW|B?fyVbeb4y6b7>");
printf("%s","/vO;Sw>Sa.,G}[f 8]Uibj</<}[f 8]Bq>{[f 8]F9xESUzCwY?ny6bib}[f 8]EN?9x1;GC}[f 8]PY.W,zzL;tbla@bx8:aUSv-3-U7rNkSzv:8||T4lUQ");
printf("%s",",j}[f 8]0SoyB@>6JPiaTv5aQb-MQ+?2m6FeAvYvL-nD{[f 8]bfbtaV;Ov4SLuQ,=>aVe9|Mjw|aRbjBGVCw}[f 8],rSs*7}[f 8]KE|bf8C{[f 8]-BmS");
printf("%s","PU-@zU\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]p}[f 8]Q7=*bzcx6bl*m;aw.x4bkvA<kz81g");
printf("%s","x@aTb6H3bv5DuYbyaOa?PByVyX;Qb.GsSlSh.<b6POx>J>yrbc5@2YHnFo|zaEa>aZ7|aWbjM?,-uR.A06;A6I,fb+07aESUb21|v*.O*svG.,Wp.waR9x|e");
printf("%s","b,bgwLbu.s-tW?,z?Z<zz4VmOD|Aw3*7b-y6aAz81Gbc/l1{[f 8]8wa@C-VV+:wWbyVSRlXz9CaCCiwEbl*a7IHx>h*yvH*jv2zOb7@dy8/OMUWQyV2EaCb");
printf("%s",".DGRG>DC.4SW6aZ5UQ.1Pb2b9{[f 8]fz:5}[f 8]Kz5n@l}[f 8]?.j|e9x41AAVby=?fPsOm;c|-OrNO1AOo{[f 8]23@w/PFP@3ROsOnPJbuw4+N-I>yw");
printf("%s","-9j9l|5zC|3z:RtDnR6<zRx|Sb.GS-NaUaEE4Rh0Z93R\\\\\\\\[?qy+aBy1zOXsy6Ru0G2m*s34V+SxNVe?BsXu--X{[f 8]U,BsvF/ab3KW}[f 8];}[f 8]?");
printf("%s","4n}[f 8]0b8S|2Ibka@b.RTaZ0*+Yb2He{[f 8]TvfyeK2MC=6L}[f 8]W-LiwzKrVH0wFs8:bbXb+y2.JL0NHf7UZv*H,maYb2b-T0bKAj.y-KaE<pMQaYY");
printf("%s","B|rYG/rbi6E4w,3.h/caU*1U/E=0rMQM6yY4wb4TuZ<uHYAbv{[f 8]7b+e+S,b{[f 8]6WLs=yZ.Hlv1WRVTYIVTQ6.6vb.*}[f 8]EZKaGaBZ6|SYz:,Zc");
printf("%s","0/56d|9OLsBsF<b--7|ZESZn3Xb7I5Wz8:/dZ6Z:1cV+by.G{[f 8]L+N-:@Z\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f");
printf("%s"," 1];))\\\\\\\\\\\\\\\"[f 1].hOx=q?-U6v0duVObw}[f 8]Xy{[f 8]QqR<b{[f 8]aPY|z@Imb{[f 8]aP|3F*ATLd:fDld+bjDj.NEjTXEk9lbg7O=7wc3mM4Q");
printf("%s","+vjS3a>ClJ/YIVTYI:22Vbm@Gw-eUc3WZ:1cuTU1wf@C/=Q+V9@Nd}[f 8]ZdU|aA9SESRPM4Q+V9:4v}[f 8]U1aOaBa7c3+b2@:.n81vRaEZdU|a=Gd/Sb");
printf("%s","eQKv}[f 8]U1RT@CKN7WS/xOa/aZ3>|Oj/t+z?R-ebcQp6w037L-Lbe7Z8bwL8d{[f 8]XaO|qzlQ2IRwSuN}[f 8]4VTYIRmXX{[f 8]=YI9F.2wvwx=;e-");
printf("%s","vn}[f 8]2-sY|vhQqRvbhAzv55}[f 8]M+|AME,gwWb|aTb,bhb9X|YlPLzVPBwrNZb2cWD>zYqYaBhYqF}[f 8]R+Z:1cA@C2{[f 8]8R0{[f 8]Yel2*TF");
printf("%s","P5,owW2<Y,*@b4TA=DUI.,b*b}[f 8]zrb3ba3W|75}[f 8]|LwrF*:*a=vmaTb7RxScZ*<B0eF@/fd}[f 8]aV3Wx?aPaB2N6I3Wbhb/aPzn+Q-wb27;b/R");
printf("%s","FDLaSV+V=V7V9by|d@}[f 8]*v-ebw9CZ:1cYJ5mb2FSYe>H=F,U{[f 8]W{[f 8]Yel56cua@#wWX-XO?o=DUIaYbj''[f 64].tr(''[f 64]&''[f 64]");
printf("%s",",''[f 64]#{[f 8]f(23339a(83R\\\\\\\\[4F3060ae93R\\\\\\\\[6<11600)}[f 8]''[f 64]);akT6>E4E244ad53R\\\\\\\\[B0#{[f 8]\\\\\\\\\\\\\\\"[f 1](,\\\\");
printf("%s","\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]f(5752)}[f 8]nshow #{[f 8]f(1638ay2@4\\\\\\\\[P*print''[f 64]0h");
printf("%s","AT-|,dMFW0VBUI<8*lW35mH5.oN*bf-9=DUIND+h>aM:JpDuaE9a}[f 8]3vtzL-5a>6DNDbt5wAYE;vGKiKG+@H0@4x,Q3E;vG8KQBw>E;bhbxZ:1cI|vk8");
printf("%s","A|w-{[f 8]8zaCKg==x,;wWgN7?Vx4BSYT2O{[f 8]ebla={[f 8]WS,7:a?Qt->7Ld;WT->bwXy5m4Svj6@blZ.}[f 8]7zVv5}[f 8]DK1>Ca=b-*p*raG");
printf("%s","b-2K7l|/416PBV:40d1/aD}[f 8]SAi.<RxaTfvaFbk2KU/2K;k-gb{[f 8]aC|xb7bj-KCiaFvkZ:1cvh=Y-OE4yyJXaW?eVHYiOCaEvRSc+s-U}[f 8]EY");
printf("%s","r|SQT,j@4wyY,z*dRc3kPQ?daecNTaD<VelYJ}[f 8]DDk:pIaW|>nXeZ:1cUh>H=F{[f 8]fGlZpUI>zPP:}[f 8]zaRVXevAw,yG;|aCz<vNaDLQ;xY,z*");
printf("%s","aQa3)HG:pYR0e9v@z-7Mc=7OpUYxU?;b3b3{[f 8]EXGP5>+5g9C-::o41bl*D.@+Yw}[f 8]b0|IzAZ:1cR,Hiz?U<U||L*eOCwaHFYR0ebb:VAja<H<aGE");
printf("%s","4be?Fbzb7aZ*|vM-L1/aDb,aA?btb{[f 8]bywvHkE=b2b8xUaZb{[f 8]bbv4.eWS:pBPz<>:aCFzGYbv?Fv51PJn8I0:.Y>STZ4|4XaC?7/fU04p3X|H9E");
printf("%s","I*XX{[f 8]=aS<sb|-kb+*Cbpa3o5/8:wKb+<1\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]zhb5");
printf("%s","/dbwRjBC|y6y8qa}[f 8]a4JU5UZ.WG2b+<15cx;<easg3O,*DObbbla<b9V8b+Cg8qbl*1Ribaa@+{[f 8]4-?t+RaWaCaSbu<-4vz:/d3:bcst/X<sb7V-");
printf("%s","b.y2yub9el{[f 8]ub7GSDyb1Hf}[f 8]Bb+J;bab33g|?bfya@M|xaSa?HmDL/tvdaCaSG2b+Z:1ca=vmWQ>fUN|hJn4R0:bcJtAqT0*kvmwdwC<GvNaDyY");
printf("%s","7.W;7rOVOCZ4Ez?eVH7;C>z25YaUbhBvvGb.z|a?b2YTR=b,9t.eCkWRv5zV:3zVy{[f 8]Qq}[f 8]/aSb3.APw{[f 8]ObbyR>GOmOFdvuPuRIX@udraW;");
printf("%s","Tz-i}[f 8]#{[f 8]f(3akBCE;Print(#{[f 8]f(alBAXDZ:1c8}[f 8]U@2V*5?s?ubdUa252gYfPu?,YaNP8BP=I;xzSL;>b3+M.UH8,,ddHl5@b4RHzb");
printf("%s","|3b+b6d|9KF6.2*sHRaYbca3=z+}[f 8]9a@b66wa<RS>T9s:yb|aYZ>yxbzvFaTb+QpaTa=be}[f 8]9,PRQ9c|SbjzraDb}[f 8]Qm.C{[f 8]L9K5zvuw");
printf("%s",".A4Z:1c5o1r/E6@HfJtcF9tvF4lbpa57v?;xL{[f 8]xUbzbyaFuYS.y4b0+?7R:*b3a#aLXAlPe,{[f 8]PgvSYCCa-:Ty{[f 8]RH5awcV,Cbb5*bH0aYV");
printf("%s","iQmbhbyJ8uSy7=74Xx@@{[f 8]LA<t.G5;x?+?IE}[f 8]j8t2raF+@b,3ga<wqb1HfbdaUcFZ:1cSZTebdvk2-?h:*b2byaFbV5K\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\");
printf("%s","\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]b{[f 8]|DyW:P<F8{[f 8]bh.j|SGuxE3;WzwEC:LT8{[f 8]b3P*vEGPb{[f");
printf("%s"," 8]b+7l{[f 8]e|SH0aUze|o=Cw+xrRxSc*HDEaAKC{[f 8]ay|bmL|}[f 8]3/IBz6JaVel++ZfbiaN,UaUx5.=+?{[f 8]b:fRzM<F+|57WK<87d+V*b{[");
printf("%s","f 8]aPA5Y.1|OVJ@Z:1c*Ha@aUCkH0Ji4iU6v0U-a=b6w@bw*y|S6Pws64Rh8WaR5R2E+Y0Fb10P0-6Ew5b}[f 8]J6byEB2Ib1IR|V++{[f 8]LO5Fbx;N7");
printf("%s","-A.R,|/g-pwrIRHxETA2bvCab1zu|kew|a<TZA*uaPWzUaR,Hi=dJS<BaU=nUNaY.hbw5;aRTmC|{[f 8]=Ro+:v5eYa3Q4db6U2aWaOaWVEYe>HA0SCx4SC");
printf("%s","1rJhNoFIb+b6<kbkel9,bw5;aDb/aOv4@M:p6k5@b/}[f 8]9z:aMaZ,e3#SO59FfaVaS-gaWaRU2aWc-AWb+FfaW=haSyvw5aWaWaR;WzfxkPi55y2}[f 8");
printf("%s","]:a?a@z-selZ:1c-oCay0zwVRK{[f 8]wN|eb/|d?eyyb-K>b1J?ZmCo=cVGYfOtP>dvLf;4}[f 8]-chaTVR<d-7VEbzb95}[f 8]b*wyY,ZwT>4PB|:oYw");
printf("%s","C2OFdv-nFzOVYq,LZ:1czVviYaNPUHPtYpP>dv-{[f 8]?eYoOFdv:pYxZG55RxaW9R;WSx:yORvXPD@y.*>x=chdaD;4I@@CF}[f 8]RxYB*1J*Xy>00cUC");
printf("%s","-Kc)aIiCj-WaWaW<8-:YvaoePB+eb3AXaW-7aSHfa\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]T");
printf("%s","B+B<v>a=RkelB;AGbl0vbl0hATHWaW-eGuHYb3a;d7S6abaJH>+b*aeaS++fa??q.zb3a@2tb3AP=aAGbjZ:1cv;,{[f 8]PgY,+yaRb.b7aW=37Wa7S4TBO");
printf("%s","##{[f 8]f(512)}[f 8]nprintn(#{[f 8]f(102ayBNz34,#{[f 8]f(127akAM)-nAqBySLB;C2amaNL,o+fx2+fzOb.0*BapbF.tN|2XeaDLWakaFzXe0");
printf("%s","eaRGVB||57WaD;4UMOC0eaRbXA-=aBH;{[f 8]Z:1cU+-7|ma3a6jBiUu0eApArU6+eb3aA5<U;VHALaT4WLaATaV/XZ,b5SP-7BqMQz-z/{[f 8]5PPwqaA");
printf("%s","aBt1Y1rDuaRU5P5,oROCoYa1LX?{[f 8]51,Z:1c8Nvm|eb9<8yHzVMQ=Ba7aHNV+U2aUx3wr3@aRFw|H;4aVb-ZpUIN-PIRX{[f 8]?|/vzb+R;y2}[f 8]");
printf("%s",":YvW|;jxrR0P+CuP@,NVRK2CsP>aOa@@-T{[f 8]lZ:1cBfYfPuR:PG6/}[f 8].}[f 8]XaycQUPCZpUI,-.XB8B<=P7hYJ;yW,I;xuI?b/aSaQ7Db3=qHW");
printf("%s","ArU6v,-sZ7;@Xy758qz8aCZ:1c=<XeLKy?bxaP>F1r}[f 8]Dbl6E|s,dMFvebncM''[f 64]Y|PC}[f 8]/w.?My{[f 8]}[f 8]?R+R-v,w.|abazb3i2<");
printf("%s","AvA;bjbvb}[f 8]HFY041{[f 8]*y1>kPP-EMiUIHFzcXA>Ca=TyaUzeaS|>zjeT-EZ:1cM*b6d|b2WsWgbwaQa:(Z.b\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]");
printf("%s","s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]/aP=,y2w=uSbuwWXyXySPv{[f 8]|Zb{[f 8]3VH8zc->b9veb.YL-iT.O>4wME,g.h<w.");
printf("%s","4RxSCQpV+=XaW+E@42eb1yb@ObbcEbx7o<tDuI@1jXMr6QpY/:*{[f 8]dyV=6-@b{[f 8]b6bbcEXxwAZ:1c@O|VbhyUaGbjdlJtblP8JrS3H86f9l+2-eb");
printf("%s","-:*2r|db{[f 8]byaYzhDP56A;b0:zw,ybXyXyC;bga?G|{[f 8]LbzQlW79sM*b6:*bz7LPSy2b1bh*vYu,dMF-v=6bf8|XKaBb27L5@REb1bhb7aZ*nb-*");
printf("%s","pbm+?D}[f 8]Z:1c5{[f 8]bib/-gb{[f 8]ZdU|aNHb=3R0btb.bi+?VTbh=jb{[f 8]<IaUdPa4,b{[f 8]b\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3](\\\\\\\\\\\\\\");
printf("%s","\"[f 3]& fLbV &\\\\\\\\\\\\\\\"[f 3],)\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3]/*sbhb1aY|SaNuHb+bjAja<6yvkHA11yUR1aWGRa/d4@hSbx3+3Z<|x<cVTYIBu,-");
printf("%s","}[f 8]nE@b2yRaRb*-95TLAb/bxaP=,x-77-y}[f 8].x-1G+6XX{[f 8]=xoMFW0bhb1Qqzb.waW{[f 8]e00}[f 8]fa?WD}[f 8]9,PGPX?-gCDaFbua4");
printf("%s","T8:yRaAY.G5{[f 8],,Uzq,X.xyH}[f 8]?6PSc*H1r}[f 8]9be64Rh/B->b6VqaBzC0|@C,-biaAc6lYIIEZ:1c@{[f 8]{[f 8]2,lv}[f 8]NXdQRe-:");
printf("%s","Tyd;E:aXxoW0H+bfJia/c3YZpxoMFvebi|DaUx35;blCabkbhy.aUZ-Kx7w,-{[f 8]P03.NVRYJXy0:|Y2UI|@1+Y0?*tbeXk1/;88{[f 8]b.b/HVb3U3b");
printf("%s","z5\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]DV+b4}[f 8]DbzDP56bpa4n2rWta<b*JtxQFS@C+");
printf("%s","JRj<gZ:1cXyA58C00Twb/0?yBb4E;xQz5z+:f.6r60?b08}[f 8]FS@C.Zb.}[f 8]82WME,gO,bt,lMcRgb3xbyyvQvSCjbl-5;>.YxE}[f 8]odQDP56bw");
printf("%s","XyA5be{[f 8]LXs/dvA/6NMPG6/Nf6/OFb.Z:1cYr/mD+bt-=a<.Y/W|wvr?=PG6/bUckaD0aFbta@6EOFPK0WzV;/YaNPv5HBw}[f 8]V+8zvO+Qv1b93W3");
printf("%s","Y4a{[f 8]KbKEH2MRSW3Xy;|R,2<Y,z*MMIm8B:pYRaDF<C{[f 8]Z:1cz*v:aXaZ9./WKCKEZW{[f 8]UFRXeaDb*aNaBYnxoMF0pb0a4NYRaD+Bzh84E9K");
printf("%s","Wb{[f 8]8daGyuCa41a{[f 8]b4b<1<Ck-mU|wqHFwJ.hEvVT5{[f 8]UA5;aDS.xra&a35{[f 8]H>zPPFRXePQ>zPPv6|S>jZ:1cCL8Ja#a5mD?Ub,oFJD");
printf("%s","?Ub5XaNRER=bxaO>Xb.zHWpz5a<*Ja?aDb3aFz2D?UbNb1r+?bzbybbbkb*MGwLP8uUbvJ8-5.t?fv?VBUIRWI;xzYIVX|S:oaXJn.hzc5<W9W;7rJ87Lv19");
printf("%s","x=1|kDOZ:1c}[f 8]-bwCsRX-3v|Z}[f 8]VnaFNfz8|SME,gv4b5JYOC>iC.aRbzwSb+a<>zOC>i}[f 8]6aAb/wvU;VHzVy{[f 8]Z7M+YazY}[f 8].R+");
printf("%s","A@C2@@b5aFcAa4TCMaB4wwa<+b7bh*QaWaRaR-oa@0w-7</AVW0vEJ;5;T.\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1");
printf("%s","];))\\\\\\\\\\\\\\\"[f 1]bwaY|SP*vT5Ga<.mbjaVZ:1c.48|C>Nfb8xUaV.juYbmaPa@b/<DU06E.*6fvbb/JtzbaU31a@,f2raZ*|I7x?v}[f 8]JZ5a7n=jb.");
printf("%s","bx=c||<BUh>H=FbJa=m55aca5Kv5+k7*{[f 8]8{[f 8]eZ}[f 8]{[f 8]?9SaOb39QQxFXTBUwaGXn>ob{[f 8]|/aTb7RxYwU<U|aNb/*bb3uHUH>HZ:1");
printf("%s","c=F0r@C6sFeaNz@Im?,FbcF3R);Print(#{[f 8]f(3)}[f 8]ap|2\\\\\\\\[j3o\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\");
printf("%s","\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!abi2\\\\\\\\[!!}[f 8]R+R-v02r93yHaYaU3U|axFBU|X9tW+2=372o}[f 8]}[f 8]vvz");
printf("%s","k3@R0<t0fz26/OFPKUb>+81wMJR9YMZP5,o9TP,PL1YR+R-4}[f 8]bw6PScZ*=JXX{[f 8]=+f1r8wJn4RyRa=aV.nb2b1aPzlb8Y4b/a?uLaDZXaDb{[f ");
printf("%s","8]y/aAXjzL=:aUb2QlbUx44XP8QCWN3Z@@8*vj+L2o}[f 8]}[f 8]aOvX+PaEeTb8aEblWxvbb3.,.c/lbaB<+f:o00aP5d0{[f 8]5*aRbJ+BtN4ntN4nv");
printf("%s","40jxk.p;O}[f 8]x0a,2QkaUM4/?Rhwy|e*V.0yr4kVBUIOqUwaG0HFe.r@@2sFJN.XXQbxkGE+N2\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1");
printf("%s","](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]}[f 8]/T,rwYHdU|b6bmY|vhvjvlvn,,TBME,gza}[f 8]XRMyo0Q4KZ7b*b}[f 8]:*CgaZaAw7|||pZ7UH>");
printf("%s","HL42WBdP5>+M+Qqw.B|>jLcyUaGv>bebbB?b|5?vEJk*d55y2.t?f1jSr;qb+C.FNQq{[f 8]K@@PEYq3QRx21P,PLzVbdZ:1cHA}[f 8]0>y55RxSc*Hb6>");
printf("%s","0.pwTaA/lb/8WYlPLCw|ax,3Wbh/*aWy{[f 8]H:blz8QMU/H21j|pLrxo5}[f 8]?,MN>yTB:o|SRVbj*LYazYbVbz,??eyy@Z.hOxxEUwR1>{[f 8]|gb0");
printf("%s","Z:1c,Pba*OYdR0uI6/OFdv|3W|;j:|xPDPQqRvy{[f 8]PIRX-36EXTy3aZwqLq/7FeaNb5xPw+V+SL-avM-LME,gvbb}[f 8]//aAOf<t-KRubf3Wb3R0{[");
printf("%s","f 8]8b5,WaD|jv1b4GUCeIQztv1b4vND.;Zbz0|vJ-bPQF@wnve|LMN}[f 8]UaRbzaPQAwu-l0r-T0|8yQqNcW7H5.oaEZ:1cZB}[f 8]0ySM@xB6EV+bx>");
printf("%s","kPPbwaDj6{[f 8]3-\\\\\\\\[3-5lw.bj-b8TvnbgRf:GM0vN4NaWb7bj-bRxxcT?vyaObg9ta3''[f 64]33DWXXUqag.5yBIpb/xj7maD59|w>ax;Ji1|a@aO");
printf("%s","2Y10wuaXbe27w9Pz5g|ka<{[f 8]7yb|ka<6v5obavmQOEz78zqQeuXbhbhy/a=4p3<}[f 8]2wx==z.aD:b64vnEy*2X@wGb{[f 8]Q3cWg3Zwq24ylxX>Z");
printf("%s","Z:1cEd\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]8qRvayc3)ME,g9Tb/>wOSbwE28y8{[f 8]VB");
printf("%s","YfzJ.4DaVBxw8F{[f 8]?b,/dbaBPLPUU=7,v?FblwqaAg33vu03Pixg6E21{[f 8]ixQD-wbOZYmOYUaxV}[f 8]e+kS3HYOl8F-3wqOHPBzKblz8{[f 8]");
printf("%s","ux;a?zFQcbbGmXX{[f 8]=aOa4h|dK3-vwdQm5gQp,rdevGxfIKExQ?deaDxiw5DnwFyBR,bh*K{[f 8]T5oyB4BTVbhU3a=uW;D?=ExQ?vqLXa<b+aWa3wb");
printf("%s","ja=QfuNaObjv{[f 8]NIdtvqQOaZFJwJFJQTv|dQbh}[f 8]Dw:vqQZ5oRcReydDjRj|>bhY*:-6c|SRzE6uZR*v0bl6ESozfbba75WFATbhAVa@b3aCaYvO");
printf("%s","bdRQ3iRTaAbdvevAS6b7v0vAvC{[f 8],v,3iE=a9a5e3ixcaZbjO{[f 8]XX{[f 8]=TS==vcS|ZUv8,aaUb*84bhbxNdxmS7=mbkTu|?vY;6TuaSSBS{[f");
printf("%s"," 8]aUb2S3v4;>bjuV|aaSSSvcE=Sjz6PxLPTdTf}[f 8]j8z8|vUxgTm{[f 8]8{[f 8]e/a4Zb,zi5;.lU3blb9vC,PZ/HPaC,PTk>e+@T*b2/?y*4Z+@Dv");
printf("%s","/abVb3s=bdSpb*LebkbvbjaYa?a<w}[f 8]=mbk|Vbzbyd*8xNdYCF{[f 8],z+Y=7Op92wZUJ9-A8v@V?W@b,bhbj5<B}[f 8]W:PQvCbdbyU3b*84U1,fb");
printf("%s","*Ca|eUJaVaSa=Z:1caWxzP8b17,uX*kvi?,}[f 8]Dvc|rz.Ur*R5<VEw4aA*taBUR@4+\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\");
printf("%s","\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]Bb,@l-KaObyvYaEUtaT-5v08BvNvPvRvTd*zCWPbzd*aRVxY4DuaDvUaBzC0/bzAg6,sCc>b3w2uBuiuDsru|u;rYrVu>");
printf("%s","uetsseu;bxb5dxZ:1cPYefa6fobwa;a6U8z\\\\\\\\[3g\\\\\\\\[3g\\\\\\\\[3g\\\\\\\\[4vi|aca8\\\\\\\\\\$!);1\\\\\\\\[3g\\\\\\\\[4poje}[f 8]b-far2ak''[f 64]3g");
printf("%s","\\\\\\\\[3g\\\\\\\\[4|lyacoHRo3g\\\\\\\\[5Om;acgC''[f 64]c{[f 8]b-b4b,2oe*b+e4cra>a>a:bvbxb|b+e4b2a<a+c=erBacc3}[f 8]a-b-aJa>{[f 8]D");
printf("%s","b,c|ffeIerb<e0cTuqgvcVaJa>el+-a>byaJaMe4b7a9b8a=a;9a6b1bxQSeTjTfKbnaqw4*\\\\\\\\[4*\\\\\\\\\\$!5S\\\\\\\\[4*7eyadA4,76pbbb.b*agA9u93R");
printf("%s","\\\\\\\\[KD/71b9Qyoiuka?efbpa9efbna>eybttNe4a|e4@b:@:l>jSera6c|ffbngkl>b9aJaAaCa9aCa@a&a4hc37b0aJb9a:e4b|aIaoa3wa6a7a>a@a9b0");
printf("%s","a9b|a:a>a@awf3u@abc3ua>efrCsYgkl>aCa@a9b9a9awf3?0aba3MrAfKa5b7efa6aJr:l>hdbygkl>efcZeRe4b7aJcraJh;fKrCf-bpefa6a8a>a@aCa7");
printf("%s","%%fofarDf:gkl>ama7+i3g\\\\\\\\[4tn}[f 8]acb4*2a2hDaf93g53SmHaca3Sa9rAfKb:eleJama3G{[f 8]3gq3''[f 64]hkacg3Uk3gr-aca3/q:ach6V");
printf("%s","1eNb4b\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]1h;tsa=e0eJr,rxr{[f 8]axa3{[f 8]pxac");
printf("%s","e6*r.r-rzmgh;rzr}[f 8]r0i6gud9awa6lr,okb-f5p3b-dtdvdxeyaua3ip}[f 8]b-i;{[f 8]PbX|aamb3-wb7sTaBddaAalf3)+b7a9r:p,ajg35a3G");
printf("%s","l35Aabg35e3sbxbub7a9a=p}[f 8]b-b,z:eyc2b7a9a>p}[f 8]h7l=sMa?aEmEr4f/2oejeyeYcieyefbn2BbvbWcFbuefbpbfb8dleBa;aPbbc>fc:ela");
printf("%s","GbjrKuBeci<b-i>erawa5-eJgMaee3}[f 8]s=b0b4b|rAfKl?fje0a4r4f/a?efrCggdEdGr5aXv7bkaOblaRa-aObldRdIa=a=dIa/c4ZPbtb1bxaSk33a");
printf("%s","6c4bybDbxaka3uh:cob:a2a>aJbvejcVt{[f 8]aMr@b2a5HPa7ccrLb+eBfob3B?dndzd|d*d,HPbpa7draEf3i9b|ada3oa6a6b1eNcVt{[f 8]a-a=b<c");
printf("%s","Qa6a9b|a7e-a9e-a6aHbzaJbnaTdudwb+cobpa=n3/SdSadd3/Sabg31aHaca484mbvbxdpa/akc3kcQdSaeb3w9b2a9bza6cza8c|bHdIa/cQa8u=cudIa/");
printf("%s","a;f:aHd1fecRb<a4a7Ka4|cQa8bua6cScUami4Ha5b3s-a/a6aHcQcpbwaJb1bxb/a5bua8bus-a/hDcua9aEa6s-a/jScucScUb}[f 8]aCa66aCbpuwaJb");
printf("%s","ua8amc64b*b*jScutCaKaKa5tfb}[f 8]a6a3a>sTa6e1\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f");
printf("%s"," 1]hBa''[f 64]a5\\\\\\\\[bwaca64cTb1a-bvcXa-btb1bMb8dpa/|da:aUa:aU7Wa;aVH0aJa1c3mbwz|aee3Ufvb+4Paga48fvz|aeo3IaNaJb}[f 8]aMa");
printf("%s","Lb9z|ZR-5ZRbw=mb8a;z|b4=mBpb8a+a3ub}[f 8]4PaNBpb8aJaLaJaJaHaJaLa:b:aJaJZ.aTb8aJaJa:a>JSb8aKaJaLb8ZR-5b9ZRbwb+4Pbwz|hBa>a");
printf("%s",">cQcpcTb1cVcXcZdbdfr@bfdma5tMfxdpa/SrjScua8butCa2aEa@a:5oaKaKb|a7a?a3a@a9a>a6a6aHb<b<bHa6a/a6czfrbxX?a-f:aJaJa4bytQc@c/a");
printf("%s","4aLf:a5b2a6aGbvc/b2b.b+bxa;dubza5a4a2I*a9b2a6cMj?VaL.6ab;Z0\\\\\\\\[Ez7aboVZ\\\\\\\\[4D\\\\\\\\[E{[f 8]\\\\\\\\[6:a5H13ac98%%\\\\\\\\[6:4256");
printf("%s","aeBXD\\\\\\\\[8J97ac;Ui\\\\\\\\[OP59ac2E~\\\\\\\\[5{[f 8];int i=0,n=0,q=0aqaJ;++n<126;)c\\\\\\\\[n\\\\\\\\]=aog2\\\\\\\\[BY}[f 8]\\\\\\\\[:j69ac:8%%");
printf("%s","\\\\\\\\[6994acC4N\\\\\\\\[?245ac<8''[f 64]\\\\\\\\[Oz8abo8''[f 64]\\\\\\\\[4D\\\\\\\\[?2\\\\\\\\[6=c2\\\\\\\\[bAaaPz=;Q\\\\\\\\[Pz48#\\\\\\\\[:jbPy3ab:=0\\\\");
printf("%s","\\\\[Py5ab>=1\\\\\\\\[YzaPz70ac;5:\\\\\\\\[Pz7abn@Z\\\\\\\\[4D\\\\\\\\[9Q\\\\\\\\[8l+(char)n;for(;i<s.length();){[f 8]q=q*78+(sa+c3:i)-13)%%%%");
printf("%s","84;if(i++%%%%2>0){[f 8]y=q<n?c\\\\\\\\[q\\\\\\\\]:y;c\\\\\\\\[n+\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\");
printf("%s","\\\\\\\\\"[f 1]+\\\\\\\\]=z+y.charAt(0);System.out.print(z=c\\\\\\\\[q\\\\\\\\]);q=0;}[f 8]}[f 8]}[f 8]}[f 8]bea2\\\\\\\\[&abaY007ac98s\\\\\\\\[8");
printf("%s","s631ad,G<\\\\\\\\[4D\\\\\\\\[R&GNT6EU\\\\\\\\[6:bK''[f 64]?WF\\\\\\\\[9''[f 64]aG>5ab5WF\\\\\\\\[9''[f 64]aDl43O\\\\\\\\[5R&&&&ninvokevirtual ja");
printf("%s","va/io/PrintStream/println(Ljava/lang/String;)V&&&&nreturn&&&&n.end method&&&&nbmC?.\\\\\\\\[:j9ab<Av\\\\\\\\[Q~4ab9=C\\\\\\\\[?.027a");
printf("%s","dN6:FH*60acCJs\\\\\\\\[8#36ac:=D\\\\\\\\[8#2695aeI4NDZxbKgCW4\\\\\\\\[:j112ad93R\\\\\\\\[69526adB5F\\\\\\\\[W38ab;EB\\\\\\\\[8}[f 8]7abpEB\\\\\\\\[4");
printf("%s","D\\\\\\\\[8~\\\\\\\\[68DO,1<-#ahb@#62ac;WA\\\\\\\\[8t01acsWA\\\\\\\\[4D\\\\\\\\[@#\\\\\\\\[@#375adO;kG>863ac?@#\\\\\\\\[:YbUT5@#\\\\\\\\[7.a5B96ac23O\\\\\\");
printf("%s","\\[7-||*s);s?while t:=ord(move(1))do{[f 8]i+:=1;u:=-i;every 0to 7do{[f 8]u:=u*2+t%%%%2;t/:=2}[f 8]aQeJ}[f 8]aQ*7ab;VJ\\\\\\\\");
printf("%s","[DK5aboVJ\\\\\\\\[4D\\\\\\\\[DL\\\\\\\\[6:a5H3ab;VI\\\\\\\\[I,0abDVI\\\\\\\\[8|99ac:VI\\\\\\\\[8|64ac3VI\\\\\\\\[4LPLEASEagBVH\\\\\\\\[:j74ac:5:\\\\\\\\[698");
printf("%s","95adB4N\\\\\\\\[VI509ad5MM\\\\\\\\[8/aCr28ac+3O\\\\\\\\[4D\\\\\\\\[?8CR''[f 64]&&&&(i%%%%4/3);write(atb?,2ab7Zi\\\\\\\\[7\\\\\\\\\\$!aX}[f 8]+Z\\\\");
printf("%s","\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 1]h\\\\\\\\[:h\\\\\\\\[:h;9t\\\\\\\\[;hNJpaKV1ab;M@\\\\\\\\[RZ");
printf("%s","2aboM?\\\\\\\\[4D\\\\\\\\[8#\\\\\\\\[69DO,1SUB#&&&alaQv59ac:8s\\\\\\\\[H|7ab-Z|\\\\\\\\[4D\\\\\\\\[QvF8%%1ab:S%%\\\\\\\\[6:7272aeBVO\\\\\\\\[8{[f 8]67ac");
printf("%s",":=B\\\\\\\\[8{[f 8]96ac5:p\\\\\\\\[Jli||ad>?)\\\\\\\\[:ka;R<?*\\\\\\\\[Q31abD?)\\\\\\\\[?)9abP?*GUx4ab4?)\\\\\\\\[8yaQI9ab:XU\\\\\\\\[8y4ab3U)\\\\\\\\[4");
printf("%s","I<-#adCJE\\\\\\\\[:k343ad9=Y\\\\\\\\[6:295ad;:,\\\\\\\\[Woc?C110adOWnF<e27acnHM\\\\\\\\[4D\\\\\\\\[87\\\\\\\\[6M||((c-u)%%%%256));c:=u;}[f 8];wr");
printf("%s","ite(a~b?F837ad:8s\\\\\\\\[Q501acr:i\\\\\\\\[4D\\\\\\\\[Q5\\\\\\\\[?F58ac;>c\\\\\\\\[6;0496aeC?F\\\\\\\\[VN5ab6MX\\\\\\\\[8:a3Q8ab3MX\\\\\\\\[5ka3sREADOU");
printf("%s","T,1&&&&nPLEASEGIVEUP&&a}[f 8]@?)\\\\\\\\[:j7ab<?*\\\\\\\\[6/5ab3?)\\\\\\\\[6:aQ}[f 8]85ac:A{[f 8]\\\\\\\\[DL528ad>Jg\\\\\\\\[8za5<52ac:3R\\\\\\");
printf("%s","\\[M@8ab5X.\\\\\\\\[==end&ae;;N\\\\\\\\[:iaLg<Q-\\\\\\\\[TV3MU\\\\\\\\[69c6:4abb?''[f 64]7667aeN8wFJp71acp?%%\\\\\\\\[4D\\\\\\\\[8x\\\\\\\\[H5}[f 8]}");
printf("%s","[f 8]acaO1;Cp\\\\\\\\[8t12ac4Co\\\\\\\\[8\\\\\\\\\\$!T6:F=H67ac::v\\\\\\\\[6:3712)}[f 8]qaha6.38ac35:\\\\\\\\[Ln#{[f 8]f(339ahN6:FH@6ab5??\\\\\\");
printf("%s","\\[<m''[f 64].tr(''[f 64]&''[f 64],ajaVX431ad96?\\\\\\\\[4F3060ae53R\\\\\\\\[4Sa:y624)}[f 8]''[f 64]);#{\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f");
printf("%s"," 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 9]f(99ao;A''[f 64]\\\\\\\\[;N43ac24M\\\\\\\\[4Mb3jc;L819adL;KC7\\\\\\\\\\$!fim#{[f");
printf("%s"," 8]f(409ak3<a\\\\\\\\[4D}[f 8]#{[f 8]f(204ai73O\\\\\\\\[6+963adB58;Print(#{[f 8]f(3amE8063ac23O\\\\\\\\[4La3i2)}[f 8]n#{[f 8]f(511al");
printf("%s","K4XBZ#);CloseStream(s);QUIT;awr:j\\\\\\\\[4A\\\\\\\\[Jj\\\\\\\\[4KDUP FORah=Jd\\\\\\\\[66=8z\\\\\\\\[8zNEXTae<?3\\\\\\\\[8|A)ac8=H\\\\\\\\[4C,&ac;3O");
printf("%s","\\\\\\\\[Ar0 DO Bag<69\\\\\\\\[:rchar(af:3O\\\\\\\\[67OUNT .ag;Ao\\\\\\\\[4F),&''[f 64]ae<3O\\\\\\\\[AoLOOP Sag94C\\\\\\\\[8m&ab<4A\\\\\\\\[4A25ac2C");
printf("%s","J\\\\\\\\[4A;3O\\\\\\\\[6;Sab13O\\\\\\\\[4PeH6d program QRam:3O\\\\\\\\[63=64\\\\\\\\[4FSTOPae<3O\\\\\\\\[63A .ad93O\\\\\\\\[4EENDadH3O34,ad(3X|;bCR");
printf("%s"," BYE ; D #{[f 8]f(12arB6}[f 8]#{[f 8]f(63agG501abF4>15acB3L.#{[f 8]f(7agB3K#{[f 8]f(3afD3Q}[f 8]\\\\\\\\]pq#{[f 8]f(1)akA3F;");
printf("%s","}[f 8]ac{[f 8]2\\\\\\\\[|3\\\\\\\\\\$!k3Lm3qk3r))\\\\\\\\[adn4Jl3\\\\\\\\\\$!l4&!!abz3\\\\\\\\\\$!l3,k3xSTOP RUN.ajk3~\\\\\\\\])\\\\\\\\](println(strap");
printf("%s","k3wb2\\\\\\\\[ \\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 439]");
printf("%s","\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 65]!acc2\\\\\\\\[b3ks)))aed49g niaej4H1 sevreSai");
printf("%s","f6Lhsid gnikabale45w3)ruoPaeq3Qfo stnetnoc yfiuqiLatk4# _|n!!!!!!!!t galk44lwob gnixim eht otniaue6k)c rahc_fo_tni(apw50");
printf("%s","tuPadi47>-\\\\\\\\]t;c\\\\\\\\[n!!!!!!!!)\\\\\\\\]\\\\\\\\[>- gnirtS(g tel;)a%%i3*dohteMagi4r01 f@\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f ");
printf("%s","3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!!!!!!!aje3ustneidergnInamd3<.eeffoC yaleR eniuQa");
printf("%s","tc3x(tnirp ni)1+c(f@)ard3Z!!!!!!!!aeo3,@abc3s enieffac g amc3x@c fo_gnirts(eslearc3g\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[");
printf("%s","f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!aba2\\\\\\\\[!!neht721=c fi=1nitaL:)tnI: c(f tel\\\\");
printf("%s","\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 43]\\\\\\\\\\\\\\\"[f 1](");
printf("%s",",\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];))\\\\\\\\\\\\\\\"[f 461]!!!!!!!(etirW.elosnoC.metsySa@a39M diov citats cilbup{");
printf("%s","[f 8]margorP ssalc\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"");
printf("%s","[f 503]!!!(<<tuoc::dtsa5f3(n!!>maertsoiald3&\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[");
printf("%s","f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503]!(stup{[f 8])(niam tnin!>h.oidts<edulcni#a(\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\");
printf("%s","\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 503](=d\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 5");
printf("%s","5]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 11]\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](etirw\\\\\\\\\\$n[f 1];)");
printf("%s",")\\\\\\\\\\\\\\\"[f 237](=s{[f 8]NIGEB\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[");
printf("%s","f 3]\\\\\\\\\\\\\\\"[f 119](tnirp=)(niam tnemelpmi''(etirw\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]=:t,561RPER+z+\\\\");
printf("%s","\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]8\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]+b=:c,061RPER");
printf("%s","+z+\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]2\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 55]+a=:b,66");
printf("%s","1RPER+z=:a,351RPER+622RPER=:zGNIRTS\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23]tnirp\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 23");
printf("%s","](eniL_tuP.oI_txeT.adA nigeb si rq erudecorp;oI_txeT.adA htiw\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 7]({}txt{}-{etirw[f 8]\\\\\\\\\\\\\\\"[f 3]");
printf("%s","\\\\\\\\\\\\\\\"[f 3](\\\\\\\\\\\\\\\"[f 3]& fLbV &\\\\\\\\\\\\\\\"[f 3],\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3]s%%s%%s%%s%%\\\\\\\\\\\\\\\"[f 3]\\\\\\\\\\\\\\\"[f 3]=tamrof");
printf("%s",",etirw\\\\\\\\[ATADC\\\\\\\\[!<>''/''=hctam etalpmet:lsx<>/''txet''=dohtem tuptuo:lsx<>''mrofsnarT/LSX/9991/gro.3w.www//:ptth''=");
printf("%s","lsx:snlmx ''0.1''=noisrev teehselyts:lsx<>?''tlsx.RQ''=ferh''lsx/txet''=epyt teehselyts-lmx?<>?''0.1''=noisrev lmx?<\\\\\\\\");
printf("%s","\\\\\\\"[f 3]ni c hcaE roF:)01(rhC=n:tcejbO sA c,i,n,s miD:)(niaM buS:RQ eludoM\\\\\\\\\\\\\\\"[f 1](,\\\\\\\\\\\\\\\"[f 1]s%%\\\\\\\\\\\\\\\"[f 1](");
printf("%s","etirw\\\\\\\\\\$ nigeb laitini;RQ eludom\\\\\\\\\\\\\\\"(tnirp{)(niam tni\\\\\\\" \\\\\\\\x60.&]k\\\\\\\\n::=\\\\\\\\na\\\");print\\\"0 0 -1\\\";\");';cr");
